server:
  port: 8081
  servlet:
    context-path: /tm/api

spring:
  application:
    name: side-tm

  # Configuración de Base de Datos
  datasource:
    #url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://192.167.42.91:5432/tecnomeza_prod?currentSchema=edoc,public}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5440/tecnomeza?currentSchema=edoc,public}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
    #password: ${SPRING_DATASOURCE_PASSWORD:123}
    driver-class-name: org.postgresql.Driver

  # Configuración de JPA / Hibernate
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  # Configuración de Correo
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:manolo@gmail.com}
    password: ${MAIL_PASSWORD:clavesegura}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# Configuraciones personalizadas de la aplicación
app:
  edoc:
    config-dir: ${APP_EDOC_CONFIG_DIR:./config/edoc}
  
  # Nueva sección para Sifen (Certificados y Ambiente)
  sifen:
    # Ruta COMPLETA al archivo PFX. En Docker apuntará al volumen montado.
    certificado-path: ${SIFEN_CERT_PATH:./config/edoc/MANOLO-MEZA-MOREL.pfx}
    certificado-pass: ${SIFEN_CERT_PASS:T3cn02026.py}
    ambiente: ${SIFEN_AMBIENTE:DEV} # Valores: DEV o PROD
    # Configuración CSC (Solo necesaria para PROD, valores por defecto de prueba)
    id-csc: ${SIFEN_ID_CSC:001}
    csc: ${SIFEN_CSC:62929aDE33251DE7B32C8f9164DBe4Db}